language: java

## do everything in HermiT directory
## this installs dependencies. Ant needs no installation because they are already there.
install: cd spark-twitter;mvn install -DskipTests=true;cd ..

## do the tests
script: cd spark-twitter && mvn test

## a single JVM should be enough.
## Adding openjdk7 is probably a sensible thing, but means I have to 
## edit the ant build.xml file which is unfortunate.
jdk:
  - oraclejdk8

## I will need to set something up to catch these. 
notifications:
  email:
    - rabin.banerjee91@gmail.com